
login_caption = "SSO Server"

data_store = "/tmp/sso-store"

allowed_continue_domain = ".?localhost.net|.?example.com"

[ldap]
uri = "ldap://127.0.0.1"
default_dn = "dc=example,dc=com"
admin_user = "admin"
admin_password = "123"
